# Create Analysis_With_Regions.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

In [3]:
regions = pd.read_csv("regions_matched.csv")
regions = regions.set_index(["lon_25_75", "lat_25_75"])
regions

                     ID_HDC_G0  GCPNT_LAT   GCPNT_LON             XC_NM_LST  \
lon_25_75 lat_25_75
-122.75    42.25            69  42.337058 -122.868137         United States
-119.75    34.25             5  34.427664 -119.743693         United States
-118.25    34.75            32  34.584848 -118.131720         United States
-109.75    31.25            87  31.323486 -109.541843  Mexico;United States
-106.75    32.25           147  32.311465 -106.769657         United States
...                        ...        ...         ...                   ...
 140.75    40.75         12827  40.821641  140.745742                 Japan
 141.25    43.25         12736  43.070521  141.373814                 Japan
           43.25         12734  43.193801  141.014573                 Japan
 142.75   -3.25          13086  -3.474474  142.689366      Papua New Guinea
 144.75   -6.25          13111  -6.020131  144.970274      Papua New Guinea

                    XC_ISO_LST                          GRGN_L1  \
lon_25_75 lat_25_75
-122.75    42.25           USA                 Northern America
-119.75    34.25           USA                 Northern America
-118.25    34.75           USA                 Northern America
-109.75    31.25      MEX; USA  Latin America and the Caribbean
-106.75    32.25           USA                 Northern America
...                        ...                              ...
 140.75    40.75           JPN                             Asia
 141.25    43.25           JPN                             Asia
           43.25           JPN                             Asia
 142.75   -3.25            PNG                          Oceania
 144.75   -6.25            PNG                          Oceania

                              GRGN_L2       UC_NM_MN            UC_NM_LST  \
lon_25_75 lat_25_75
-122.75    42.25     Northern America        Medford              Medford
-119.75    34.25     Northern America  Santa Barbara        Santa Barbara
-118.25    34.75     Northern America       Palmdale  Palmdale; Lancaster
-109.75    31.25      Central America    Agua Prieta          Agua Prieta
-106.75    32.25     Northern America     Las Cruces           Las Cruces
...                               ...            ...                  ...
 140.75    40.75         Eastern Asia         Aomori               Aomori
 141.25    43.25         Eastern Asia        Sapporo      Sapporo; Ebetsu
           43.25         Eastern Asia          Otaru                Otaru
 142.75   -3.25             Melanesia            NaN                    -
 144.75   -6.25             Melanesia       Kundiawa             Kundiawa

                              P15  urban_center_count
lon_25_75 lat_25_75
-122.75    42.25     9.101015e+04                   1
-119.75    34.25     1.147532e+05                   1
-118.25    34.75     2.771812e+05                   1
-109.75    31.25     9.791077e+04                   1
-106.75    32.25     6.407468e+04                   1
...                           ...                 ...
 140.75    40.75     1.874362e+05                   1
 141.25    43.25     1.894557e+06                   2
           43.25     7.577249e+04                   2
 142.75   -3.25      7.321599e+04                   1
 144.75   -6.25      8.544281e+04                   1

[650 rows x 11 columns]

In [4]:
# Use this to create the 'cells' list you need to iterate over
analysis = pd.read_csv("analysis.csv")
analysis = analysis.set_index(["lon", "lat"])
cells = np.unique(analysis.index)
cells

array([(-122.75, 42.25), (-119.75, 34.25), (-118.25, 34.75),
       (-109.75, 31.25), (-106.75, 32.25), (-106.25, 28.75),
       (-103.25, 25.75), (-102.75, 20.75), (-99.75, 16.75),
       (-99.75, 17.75), (-98.75, 20.25), (-98.25, 34.75), (-97.75, 25.75),
       (-97.25, 19.75), (-96.25, 42.25), (-91.25, 14.25), (-90.75, 42.75),
       (-88.25, 15.25), (-87.75, 42.25), (-85.75, 42.75), (-84.75, 42.75),
       (-84.25, 33.75), (-79.75, -1.25), (-79.25, 44.25), (-77.75, 21.25),
       (-76.25, 4.25), (-75.25, 7.75), (-73.75, 18.25), (-73.25, -40.75),
       (-73.25, 41.25), (-72.75, 10.25), (-72.75, 46.25),
       (-71.75, -35.75), (-71.25, 10.25), (-69.25, 9.75),
       (-65.75, -27.25), (-64.75, -21.75), (-62.25, 8.25),
       (-60.75, -32.75), (-58.75, -38.75), (-56.25, -25.75),
       (-54.25, -31.25), (-53.25, -26.25), (-51.25, -22.25),
       (-50.25, -29.75), (-50.25, -27.75), (-48.75, -2.75),
       (-47.75, -23.25), (-47.75, -18.25), (-47.25, -2.75),
       (-46.75, -23.75), (-44.25, -22.75), (-44.25, -19.25),
       (-43.25, -4.75), (-42.75, -14.25), (-39.25, -13.25),
       (-39.25, -6.25), (-37.25, -8.25), (-13.75, 10.25), (-13.75, 11.25),
       (-11.75, 7.75), (-10.75, 11.25), (-10.25, 9.25), (-9.25, 30.25),
       (-9.25, 53.25), (-7.75, 31.75), (-6.75, 38.75), (-5.75, 9.25),
       (-5.75, 35.75), (-5.75, 43.75), (-5.25, 6.75), (-5.25, 12.25),
       (-4.25, 36.75), (-4.25, 43.25), (-3.75, 55.75), (-2.75, 52.75),
       (-2.25, 13.25), (-2.25, 52.75), (-1.75, 7.75), (-1.75, 43.25),
       (-1.25, 7.25), (-1.25, 51.75), (-1.25, 53.75), (1.25, 7.75),
       (1.25, 9.75), (1.75, 12.75), (1.75, 52.25), (4.25, 32.75),
       (4.25, 35.25), (4.25, 51.75), (4.75, 8.75), (5.25, 34.25),
       (5.75, 6.25), (5.75, 8.75), (6.25, 35.75), (6.75, 8.25),
       (6.75, 9.75), (6.75, 11.75), (6.75, 12.25), (6.75, 13.75),
       (7.25, 9.25), (7.25, 35.75), (7.25, 48.25), (7.75, 5.25),
       (7.75, 48.75), (8.75, 13.75), (8.75, 35.25), (9.25, 48.25),
       (10.25, 7.25), (10.25, 35.75), (10.25, 43.75), (10.25, 44.75),
       (10.25, 47.75), (10.75, 45.25), (11.75, 2.75), (11.75, 11.75),
       (12.25, 9.75), (12.25, 11.25), (12.75, 2.75), (13.25, -1.75),
       (13.75, 11.75), (14.25, -5.75), (14.25, 9.75), (14.25, 14.25),
       (14.75, -5.75), (15.25, 37.75), (16.25, 1.75), (16.75, 40.75),
       (17.25, -12.25), (17.75, 8.75), (18.25, 52.75), (18.75, 8.75),
       (20.25, -9.75), (21.75, 43.25), (22.25, -5.25), (22.25, 4.25),
       (24.25, 11.75), (25.75, 48.25), (26.75, 47.75), (27.25, -9.25),
       (27.25, 42.25), (27.75, 40.75), (27.75, 53.75), (28.75, -12.75),
       (28.75, -2.75), (28.75, -1.75), (29.25, -5.75), (29.25, 14.25),
       (29.75, 0.75), (29.75, 59.75), (30.25, -4.75), (30.25, 13.25),
       (30.75, 52.25), (31.25, 29.25), (31.25, 36.75), (31.75, -16.25),
       (31.75, 40.75), (32.25, 13.75), (33.25, -18.25), (33.25, -3.75),
       (33.25, 51.75), (33.75, -25.25), (33.75, -16.25), (33.75, -9.75),
       (34.25, 0.75), (35.25, -16.25), (35.25, 33.25), (35.25, 47.75),
       (35.75, -4.25), (35.75, 35.75), (36.75, 11.25), (36.75, 15.25),
       (36.75, 18.75), (36.75, 45.25), (37.75, 47.75), (38.25, 11.25),
       (38.25, 13.25), (38.75, 11.75), (38.75, 14.25), (38.75, 14.75),
       (38.75, 47.25), (39.75, -13.25), (39.75, 10.75), (39.75, 24.25),
       (39.75, 43.75), (39.75, 57.75), (40.25, 0.25), (40.75, 37.25),
       (42.25, 57.25), (43.25, -11.75), (43.25, 35.75), (43.25, 39.25),
       (43.75, 26.25), (43.75, 43.75), (44.25, 46.25), (44.75, 32.75),
       (45.75, 37.25), (46.75, 30.75), (47.25, -19.75), (47.25, 17.25),
       (47.75, 29.25), (47.75, 30.25), (48.25, 29.25), (48.75, 37.75),
       (48.75, 38.25), (48.75, 39.25), (49.25, 55.75), (50.25, 35.25),
       (51.25, 33.75), (51.25, 51.25), (53.75, 28.75), (59.25, 36.25),
       (59.75, 55.25), (63.25, 61.25), (66.25, 39.75), (66.75, 29.25),
       (68.25, 33.75), (68.75, 35.75), (69.75, 32.25), (69.75, 33.25),
       (69.75, 36.75), (70.25, 28.25), (70.25, 34.75), (70.75, 29.75),
       (70.75, 40.25), (72.75, 23.75), (72.75, 32.75), (73.25, 34.25),
       (73.75, 4.25), (74.25, 14.25), (74.25, 17.25), (74.25, 20.75),
       (74.75, 18.75), (74.75, 26.75), (75.25, 13.75), (75.25, 19.25),
       (75.25, 21.75), (75.75, 17.75), (76.25, 12.75), (76.75, 25.75),
       (76.75, 30.75), (76.75, 43.25), (76.75, 66.25), (77.75, 19.75),
       (78.25, 10.75), (78.25, 12.75), (78.25, 15.25), (78.25, 24.25),
       (78.75, 11.75), (79.25, 9.75), (79.25, 19.25), (79.75, 28.75),
       (80.25, 15.75), (80.25, 21.75), (80.75, 16.75), (81.75, 7.75),
       (81.75, 27.25), (82.25, 17.75), (82.25, 26.75), (83.25, 21.75),
       (83.25, 27.75), (83.75, 28.25), (84.25, 23.25), (84.25, 24.75),
       (84.75, 23.25), (85.75, 22.25), (86.25, 21.25), (87.25, 24.25),
       (87.75, 44.25), (88.25, 22.75), (88.25, 25.75), (88.75, 22.75),
       (88.75, 23.75), (88.75, 25.75), (89.75, 22.75), (89.75, 23.75),
       (90.25, 56.25), (90.75, 22.25), (92.25, 26.75), (93.25, 20.25),
       (96.75, 21.25), (97.75, 24.25), (99.75, 1.75), (99.75, 16.25),
       (100.25, 5.25), (101.25, 6.75), (102.25, 1.25), (102.75, 35.75),
       (103.75, 28.25), (103.75, 52.75), (104.25, 28.75), (104.25, 30.75),
       (104.75, 21.75), (104.75, 27.25), (105.25, 20.25), (105.25, 37.75),
       (106.25, 32.25), (107.75, 14.75), (107.75, 21.75), (107.75, 34.25),
       (108.25, -7.25), (108.25, 12.75), (108.25, 16.25), (108.75, 29.75),
       (109.75, 23.25), (109.75, 28.75), (110.75, 21.75), (111.75, 21.75),
       (111.75, 39.25), (112.25, 22.75), (112.25, 34.75), (112.75, 25.75),
       (113.25, 23.75), (113.25, 34.25), (113.75, -1.25), (113.75, 36.25),
       (114.25, 35.75), (114.25, 37.75), (114.75, 24.75), (114.75, 38.75),
       (114.75, 39.25), (115.25, 23.25), (115.25, 24.75), (115.75, 38.25),
       (117.25, 36.25), (118.25, 24.75), (118.75, 27.75), (118.75, 32.25),
       (119.25, -3.25), (119.25, 31.25), (119.25, 35.25), (119.75, 28.25),
       (119.75, 36.25), (120.75, 16.25), (120.75, 40.75), (121.25, 16.75),
       (121.25, 41.75), (121.75, 36.75), (122.25, 6.75), (122.25, 37.25),
       (122.25, 39.75), (122.25, 41.25), (122.75, 0.75), (122.75, 45.75),
       (124.25, 42.75), (124.75, 8.25), (124.75, 45.25), (125.75, 38.75),
       (125.75, 40.25), (125.75, 41.75), (125.75, 47.25), (126.75, 46.75),
       (127.25, 45.75), (129.25, 35.25), (129.25, 40.75), (137.25, 34.75),
       (137.75, -3.75), (138.75, 35.75), (140.75, 38.25), (140.75, 40.75),
       (141.25, 43.25), (142.75, -3.25), (144.75, -6.25)], dtype=object)

In [5]:
analysis = pd.read_csv("analysis.csv")
analysis = analysis.set_index(["lon", "lat", "year"])
analysis

                           tasmax_num_days  tasmax_pct_days  tasmax_max_temp  \
lon     lat    year
-122.75  42.25 2006-01-01               34         0.093087       314.748779
               2007-01-01               18         0.049281       311.763672
               2008-01-01               43         0.117728       315.062805
               2009-01-01                9         0.024641       312.657166
               2010-01-01               19         0.052019       314.164001
...                                    ...              ...              ...
 144.75 -6.25  2095-01-01               29         0.079398       320.109863
               2096-01-01                4         0.010951       316.082214
               2097-01-01               42         0.114990       320.103607
               2098-01-01                0         0.000000       312.072449
               2099-01-01                0         0.000000       313.247070

                           tasmin_num_days  tasmin_pct_days  tasmin_max_temp
lon     lat    year
-122.75  42.25 2006-01-01               12         0.032854       292.928497
               2007-01-01               18         0.049281       291.598755
               2008-01-01               13         0.035592       292.765961
               2009-01-01                3         0.008214       288.956512
               2010-01-01               24         0.065708       290.444702
...                                    ...              ...              ...
 144.75 -6.25  2095-01-01              202         0.553046       298.004456
               2096-01-01              222         0.607803       298.183350
               2097-01-01              127         0.347707       297.702087
               2098-01-01              256         0.700890       297.619263
               2099-01-01              204         0.558522       297.589783

[34122 rows x 6 columns]

In [6]:
# Example
regions.loc[cells[10]].GRGN_L2.values[0]

'Central America'

In [7]:
# Create 'region' column and populate with correct region for each cell
for cell in cells:
    # values returns a list of regions which has len > 1 if a cell contains more than one city
    # so we select just the first value
    cell_region = regions.loc[cell].GRGN_L2.values[0]
    analysis.loc[cell, "region"] = cell_region

In [8]:
regions_of_cities = np.unique(analysis.region)
regions_of_cities

array(['Caribbean', 'Central America', 'Eastern Africa', 'Eastern Asia',
       'Eastern Europe', 'Melanesia', 'Middle Africa', 'Northern Africa',
       'Northern America', 'Northern Europe', 'South America',
       'South-Central Asia', 'South-Eastern Asia', 'Southern Europe',
       'Western Africa', 'Western Asia', 'Western Europe'], dtype=object)

In [10]:
analysis.to_csv("analysis_with_regions.csv")